### PR TITLE
Update nc-motives.tex

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pbelmans** [comment]
The updates to the notation in this pull request are by no means improvements, and make the notation in this exposé agree _less_ with the conventions from earlier chapters. I propose that the few textual changes are redone, in a new pull request.

**Comment by mauroporta** [comment]
I think everything is settled now! :D When Marco is done with the textual changes he will directly push the file!

**Comment by ghost** [comment]
I just added all the corrections I wanted. Moreover, added to the
bibliography the artice of Lee cohn on the comparison of dg-cats and
infinity k-linear cats.
Hope this time it went ok!

**Comment by mauroporta** [comment]
It went perfectly! Thanks a lot! :D

**Comment by ghost** [comment]
No i think there are problems with the bibliography no? when it conpiles it
comes strangely

**Comment by mauroporta** [comment]
Can you open a new issue explaining where you saw the problem? It doesn't make sense to discuss in this place (sorry about this pedantry, it's just that if we all learn how to use github, we will coordinate better in the future!)

**Pull request closed without merging**
